- README
- src/main/js/html.js
- src/test/webapp/js/samples.js
Fixed bug in samples.js
Added polyfill for textAlign=start/end
Closes #2
> Added support for Edge and IE 11

- README.md
- src/main/js/html.js
> Adds explicit height and width to renderHTML

- README.md
- src/main/js/html.js
- src/main/js/styles.js
> Add support for forcedDisplay

- src/main/js/styles.js
> Support for zIndex='auto'

- src/main/js/html.js
- src/main/js/isd.js
- src/main/js/styles.js
writingMode correctly sets direction (closes #30)
Fixes textAlign=left|right (closes #31)
> Fixes LTR/RTL issues

- src/main/js/html.js
> Whitespaces now removed before and after explicit <br>

- src/main/js/doc.js
- src/main/js/isd.js
Supports documents with no head and/or no body element and/or styling element
Closes #38
> Support missing styling, head and body elements

- src/main/js/isd.js
> Fixed broken implicit inheritance with <set>

- src/main/js/doc.js
- src/test/resources/unit-tests/metadataHandler.ttml
- src/test/webapp/js/unit-tests.js
> Added support for metadata callbacks (issue #8)

- src/main/js/html.js
> Set zindex=0 on HTML root container

- src/main/js/doc.js
- src/main/js/html.js
- src/main/js/isd.js
> Systematically remove LWSP at <br> and <p>

- src/main/js/html.js
- src/main/js/isd.js
Improvement based on PR #36
Closes #59
> Misc extra error handling per PR #36

- src/main/js/html.js
Avoid wrapping characters included in tts:textCombine (#101)
'outside' means 'before' for single line ruby and emphasis (#102)
> Issues #101 and #102

- src/main/js/html.js
> Fix 'outside' annotation-position semantics

- src/main/js/doc.js
- src/main/js/isd.js
> Add tt:initial support

- src/main/js/doc.js
- src/main/js/html.js
- src/main/js/isd.js
> Add support for tt:image

- src/main/js/html.js
- src/main/js/isd.js
- src/main/js/styles.js
> Add support for tts:rubyReserve

- src/main/js/doc.js
> Add missing errorHandler into reportFatal calls

- src/main/js/doc.js
> Add support for multiple style properties per tt:initial element

- src/main/js/isd.js
> Fix ruby font size inheritance

- nbproject/project.properties
- nbproject/project.xml
- package.json
- src/main/js/styles.js
- src/main/js/utils.js
- src/test/resources/unit-tests/colorExpressions.ttml
- src/test/webapp/js/unit-tests.js
> Fix LWSP in color expressions and px in horizontal padding

- src/main/js/html.js
> ebutts:linePadding emulated using border instead of padding

- src/main/js/html.js
> Include surrogate pairs in the same <span>

- src/main/js/html.js
- src/main/js/styles.js
- src/main/js/utils.js
Removed support for extraneous textCombine syntax
Fixed textEmphasis and linePadding code path
Closes #145 
Closes #146 
Closes #147
> Fix misc issues

- src/main/js/isd.js
> Only XML white spaces are trimmed/collapsed now

- src/main/js/html.js
> Shear angle computation fixed

- src/main/js/doc.js
- src/main/js/isd.js
> Fix applicability of character-based style properties to ruby container spans

- src/main/js/html.js
> Skip tts:textEmphasis processing on zero width spans

- src/main/js/html.js
- src/main/js/styles.js
> Fix tts:textEmphasis auto and inheritance

- src/main/js/isd.js
> Use initial value if style property cannot be computed

- src/main/js/html.js
> Improve ruby support for Chrome/Webkit

- src/main/js/html.js
> Improve text outline rendering

- src/main/js/html.js
> Remove unused pruneEmptySpans function

- src/main/js/html.js
> Fixed tts:rubyReserve on lines starting with a ruby container

- src/main/js/html.js
> Fix textEmphasis across linebreaks

- src/main/js/doc.js
> Increased priority of nested styling

- src/main/js/html.js
> Fix CSS ruby-align application

- src/main/js/isd.js
> Collapse whitespace during ISD construction

- src/main/js/styles.js
> Apply tts:fontFamily, tts:fontWeight, tts:fontStyle and tts:fontSize to p

- src/main/js/html.js
> text-emphasis-style is no longer set to "none"

- src/main/js/html.js
> Fixes HTMLStylingMapDefinition misspelling

- src/main/js/html.js
- src/main/js/styles.js
> Align tts:textCombine permitted values with TTML

- src/main/js/doc.js
- src/main/js/html.js
- src/main/js/isd.js
> Add support for xml:lang and HTML lang

- src/main/js/html.js
> Prune duplicate resolved font-family values

- src/main/js/html.js
> Trim spaces from `fontFamily` list entries
